# Generated by Django 5.0.2 on 2024-03-05 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panos_de_prato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panos',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panos_de_prato.categoria'),
        ),
        migrations.AlterField(
            model_name='panos',
            name='pano_imagem',
            field=models.ImageField(blank=True, default='', upload_to='panos_de_prato/panos_imagens/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='panos',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
